# Detecting protest events on my data

In [ ]:
import sys

sys.path.append("../..")

In [15]:
import torch

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cuda:0'

In [13]:
from protest_impact.data.protests.detection import load_glpn_dataset

glpn = load_glpn_dataset()
glpn = glpn.rename_column("excerpt", "text")

Using custom data configuration default-3a509930dabb81fc

Downloading and preparing dataset csv/default to /root/.cache/huggingface/datasets/csv/default-3a509930dabb81fc/0.0.0/51cce309a08df9c4d82ffd9363bbe090bf173197fc01a71b034e8594995a1a58...

Downloading data files:   0%|          | 0/5 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/5 [00:00<?, ?it/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

0 tables [00:00, ? tables/s]

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_33/1996737641.py", line 5, in <cell line: 5>
    glpn = load_glpn_dataset()
  File "/notebooks/protest_impact/data/protests/detection/glpn.py", line 21, in load_glpn_dataset
    glpn = load_dataset("csv", data_files=data_files)
  File "/usr/local/lib/python3.9/dist-packages/datasets/load.py", line 1679, in load_dataset
  File "/usr/local/lib/python3.9/dist-packages/datasets/builder.py", line 704, in download_and_prepare
    ```py
  File "/usr/local/lib/python3.9/dist-packages/datasets/builder.py", line 793, in _download_and_prepare
    if is_local:  # if cache dir is local, check for available space
  File "/usr/local/lib/python3.9/dist-packages/datasets/builder.py", line 1271, in _prepare_split
    to write the train data, then `_generate_examples(file='test_data.zip')` to
  File "/usr/local/lib/python3.9/dist-packages/datasets/arrow_writer.py", line 519, in write_table
    batch_examples: Dict[str, List],
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 1897, in table_cast
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 1880, in cast_table_to_schema
    array_types = list(array_types)
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 1880, in <listcomp>
    array_types = list(array_types)
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 1673, in wrapper
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 1673, in <listcomp>
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 1845, in cast_array_to_feature
    """
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 1675, in wrapper
    """
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 1754, in array_cast
  File "pyarrow/array.pxi", line 915, in pyarrow.lib.Array.cast
  File "pyarrow/lib.pyx", line 130, in pyarrow.lib._pc
  File "pyarrow/_exec_plan.pyx", line 1, in init pyarrow._exec_plan
AttributeError: module 'pyarrow._compute' has no attribute 'ScalarUdfContext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 1993, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/usr/local/lib/python3.9/dist-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.9/dist-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "/usr/local/lib/python3.9/dist-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.9/dist-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/usr/local/lib/python3.9/dist-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.9/dist-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "/usr/local/lib/python3.9/dist-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

In [14]:
from protest_impact.data.protests.detection import load_aglpn_dataset

protest_news = load_aglpn_dataset()
protest_news, protest_news["train"].features

Using custom data configuration protest-c0ba145d55e29542
Reusing dataset json (/root/.cache/huggingface/datasets/json/protest-c0ba145d55e29542/0.0.0/da492aad5680612e4028e7f6ddc04b1dfcec4b64db470ed7cc5f2bb265b9b6b5)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?ba/s]

AttributeError: module 'pyarrow._compute' has no attribute 'ScalarUdfContext'

In [ ]:
len(glpn["train"]), len(protest_news["train"])

NameError: name 'glpn' is not defined

In [ ]:
!python -m spacy download de_core_news_sm

In [6]:
import spacy

from protest_impact.data.protests.config import search_regex

nlp = spacy.load("de_core_news_sm", disable=["parser", "tagger", "ner", "tokenizer"])
nlp.add_pipe("sentencizer")


def kwic(text, n=0):
    sents = list(nlp(text).sents)
    kwics_nrs = set()
    for i, sent in enumerate(sents):
        if search_regex.search(sent.text_with_ws):
            kwics_nrs.add(i)
            for j in range(1, n + 1):
                kwics_nrs.add(i - j)
                kwics_nrs.add(i + j)
    kwic_text = ""
    for kwic_nr in sorted(list(kwics_nrs)):
        if kwic_nr >= 0 and kwic_nr < len(sents):
            if kwic_nr - 1 not in kwics_nrs:
                kwic_text += "\n...\n"
            kwic_text += sents[kwic_nr].text_with_ws
    return kwic_text

In [7]:
def kwic_dataset(dataset, n=0):
    return dataset.map(
        lambda x: {
            "text": x["meta"]["title"]
            + "\n\n"
            + kwic("\n".join(list(x["text"].split("\n"))[1:]), n=n)
        }
    )

In [8]:
protest_news = kwic_dataset(protest_news, n=2)

  0%|          | 0/575 [00:00<?, ?ex/s]

  0%|          | 0/115 [00:00<?, ?ex/s]

  0%|          | 0/460 [00:00<?, ?ex/s]

In [ ]:
if device == "cpu":
    n = 20
    glpn["train"] = glpn["train"].shuffle(seed=20230206).select(range(n))
    glpn["dev"] = glpn["dev"].shuffle(seed=20230206).select(range(n))
    glpn["test"] = glpn["test"].shuffle(seed=20230206).select(range(n))
    glpn["test.time"] = glpn["test.time"].shuffle(seed=20230206).select(range(n))
    glpn["test.loc"] = glpn["test.loc"].shuffle(seed=20230206).select(range(n))

    protest_news["train"] = (
        protest_news["train"].shuffle(seed=20230206).select(range(n))
    )
    protest_news["dev"] = protest_news["dev"].shuffle(seed=20230206).select(range(n))
    protest_news["test"] = protest_news["test"].shuffle(seed=20230206).select(range(n))

In [9]:
import evaluate
import numpy as np

metric = evaluate.load("f1")


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

Downloading builder script:   0%|          | 0.00/6.77k [00:00<?, ?B/s]

In [20]:
!ls models/deepset-gelectra-large-glpn/model

config.json  pytorch_model.bin	training_args.bin

In [10]:
from pathlib import Path

from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
)


def train_model(model, tokenizer, description, dataset):
    model_location = Path("models") / description / "model"

    if model_location.exists():
        return AutoModelForSequenceClassification.from_pretrained(model_location)

    def tokenize_function(examples):
        return tokenizer(
            examples["text"], padding="max_length", truncation=True, max_length=512
        )

    tokenized_datasets = dataset.map(tokenize_function, batched=True)
    training_args = TrainingArguments(
        output_dir=model_location.parent / "checkpoints",
        evaluation_strategy="epoch",
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        lr_scheduler_type="linear",
        warmup_ratio=0.1,
        learning_rate=5e-6,
        weight_decay=0.2,
        num_train_epochs=6,
    )
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets["dev"],
        compute_metrics=compute_metrics,
    )
    trainer.train()
    trainer.save_model(model_location)
    return model

In [11]:
# model_name = "deepset/gelectra-base"
model_name = "deepset/gelectra-large"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model_vanilla = AutoModelForSequenceClassification.from_pretrained(model_name).to(
    device
)

Downloading (…)okenizer_config.json:   0%|          | 0.00/83.0 [00:00<?, ?B/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/240k [00:00<?, ?B/s]

Downloading (…)"pytorch_model.bin";:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Some weights of the model checkpoint at deepset/gelectra-large were not used when initializing ElectraForSequenceClassification: ['discriminator_predictions.dense_prediction.weight', 'discriminator_predictions.dense.bias', 'discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense.weight']
- This IS expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at deepset/gelectra-large and are newly initialized: ['classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.out_proj.bias', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [12]:
model_glpn = train_model(
    model_vanilla, tokenizer, f"{model_name.replace('/', '-')}-glpn", glpn
)

In [13]:
from evaluate import TextClassificationEvaluator


def evaluate(model, tokenizer, test_set):
    eval_results = TextClassificationEvaluator().compute(
        model_or_pipeline=model,
        data=test_set,
        input_column="text",
        label_column="label",
        label_mapping={"LABEL_0": 0, "LABEL_1": 1},
        # label_mapping={"irrelevant": 0, "relevant": 1},
        # label_mapping={"LABEL_0": "irrelevant", "LABEL_1": "relevant"},
        tokenizer=tokenizer,
        metric=metric,
    )
    return eval_results

In [46]:
from sklearn.metrics import classification_report
from transformers import pipeline


def evaluate_detail(model, tokenizer, test_set):
    classifier = pipeline(
        "text-classification",
        model=model,
        tokenizer=tokenizer,
        device=device,
        padding="max_length",
        truncation=True,
        max_length=512,
    )
    predictions = classifier(a["text"] for a in test_set)
    y_pred = [np.argmax(a["score"]) for a in predictions]
    y_true = [a["label"][-1] for a in test_set]
    print(sum(y_true) / len(y_true))
    print(sum(y_pred) / len(y_pred))
    print(classification_report(y_true, y_pred))

In [ ]:
[a["text"] for a in glpn["test"]]

:

In [20]:
evaluate(model_glpn, tokenizer, glpn["test"])

{'f1': 0.7131782945736435,
 'total_time_in_seconds': 16.236549190012738,
 'samples_per_second': 33.68942461840753,
 'latency_in_seconds': 0.02968290528338709}

In [47]:
evaluate_detail(model_glpn, tokenizer, glpn["test"])

0.603290676416819
0.0
              precision    recall  f1-score   support

           0       0.40      1.00      0.57       217
           1       0.00      0.00      0.00       330

    accuracy                           0.40       547
   macro avg       0.20      0.50      0.28       547
weighted avg       0.16      0.40      0.23       547

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [14]:
evaluate(model_glpn, tokenizer, protest_news["test"])

Disabling tokenizer parallelism, we're using DataLoader multithreading already

{'f1': 0.5781990521327014,
 'total_time_in_seconds': 9.911018010927364,
 'samples_per_second': 46.41299203500875,
 'latency_in_seconds': 0.021545691328102964}

In [ ]:
evaluate_detail(model_glpn, tokenizer, protest_news["test"])

In [15]:
model_protest_news = train_model(
    model_vanilla,
    tokenizer,
    f"{model_name.replace('/', '-')}-protest-news",
    protest_news,
)

In [17]:
evaluate(model_protest_news, tokenizer, protest_news["test"])

{'f1': 0.7910447761194029,
 'total_time_in_seconds': 10.377355182077736,
 'samples_per_second': 44.32728685960806,
 'latency_in_seconds': 0.022559467787125514}

In [ ]:
evaluate_detail(model_protest_news, tokenizer, protest_news["test"])

In [21]:
model_glpn_protest_news = train_model(
    model_glpn,
    tokenizer,
    f"{model_name.replace('/', '-')}-glpn-protest-news",
    protest_news,
)

In [22]:
evaluate(model_glpn_protest_news, tokenizer, protest_news["test"])

{'f1': 0.7826086956521738,
 'total_time_in_seconds': 10.425367980031297,
 'samples_per_second': 44.12314278796508,
 'latency_in_seconds': 0.022663843434850645}

In [ ]:
evaluate_detail(model_protest_news, tokenizer, protest_news["test"])

Make predictions for annotating more relevant articles: