In [1]:
import pandas as pd

from protest_impact.util import project_root

count_df = pd.read_csv(
    project_root / "data" / "protest" / "protest_and_topic_counts.csv"
)
count_df["date"] = pd.to_datetime(count_df["date"])
count_df.sample(10)

,date,topic,count,type,media_id,name,keyword
97107,2016-03-17,anti-war,1,general,145368.0,wn.de,krieg
467916,2019-12-16,climate,1,general,143851.0,rbb-online.de,klima
1342959,2023-01-26,yellow jackets,1,general,385635.0,Eifel - Zeitung - Ihre Zeitung in der Eifel - ...,steuer*
173972,2017-09-13,environment,1,general,385563.0,Startseite - Münstersche Zeitung,umweltschutz
801378,2021-03-27,covid,1,general,143851.0,rbb-online.de,covid
1280585,2022-11-18,covid,1,general,385644.0,Nachrichten aus Amberg - Onetz,covid
640993,2020-09-16,anti capitalism,1,general,385644.0,Nachrichten aus Amberg - Onetz,kapitalis*
886255,2021-07-13,covid,1,general,385703.0,Nachrichten aus Weiden - Onetz,covid
63760,2015-04-02,yellow jackets,1,general,39005.0,merkur-online,mindestlohn
1243431,2022-10-07,anti-immigration,1,general,385538.0,http://www.lz.de/,migrant*

In [2]:
protests = count_df[count_df["type"] == "protest"]
protests.sample(10)

            date            topic  count     type  media_id name keyword
9898  2020-06-08           labour      1  protest       NaN  NaN     NaN
13421 2021-08-08  anti capitalism      1  protest       NaN  NaN     NaN
362   2015-01-25           racism      1  protest       NaN  NaN     NaN
1853  2016-05-28   yellow jackets      1  protest       NaN  NaN     NaN
11576 2020-11-29         refugees      1  protest       NaN  NaN     NaN
10247 2020-07-13         feminism      1  protest       NaN  NaN     NaN
6486  2019-03-03            lgbtq      1  protest       NaN  NaN     NaN
6871  2019-05-12           racism      1  protest       NaN  NaN     NaN
8767  2020-01-17  anti capitalism      1  protest       NaN  NaN     NaN
1764  2016-05-02           labour      1  protest       NaN  NaN     NaN

In [7]:
from datetime import date

from dateutil.relativedelta import relativedelta

from protest_impact.data.news.sources.mediacloud import get_article_counts


def get_coverage_change(protest_event, interval):
    protest_date = protest_event["date"]
    protest_event["pre_coverage_start"] = (protest_date - interval).isoformat()
    protest_event["pre_coverage_end"] = protest_date.isoformat()
    protest_event["post_coverage_start"] = protest_date.isoformat()
    protest_event["post_coverage_end"] = (protest_date + interval).isoformat()
    protest_event["pre_coverage"] = count_df[
        (count_df["date"] >= protest_event["pre_coverage_start"])
        & (count_df["date"] < protest_event["pre_coverage_end"])
        & (count_df["type"] == "general")
        & (count_df["topic"] == protest_event["topic"])
    ].sum()["count"]
    protest_event["post_coverage"] = count_df[
        (count_df["date"] >= protest_event["post_coverage_start"])
        & (count_df["date"] < protest_event["post_coverage_end"])
        & (count_df["type"] == "general")
        & (count_df["topic"] == protest_event["topic"])
    ].sum()["count"]
    return protest_event["media_id"]
    overall_coverage = get_article_counts(protest_event["media_id"])
    return overall_coverage
    protest_event["pre_coverage_overall"] = overall_coverage[
        protest_event["pre_coverage_start"] : protest_event["pre_coverage_end"]
    ].sum()

    return protest_event

In [8]:
get_coverage_change(protests.iloc[0].copy(), relativedelta(months=1))

/var/folders/6v/w9nn6c_n4qdbrjwfnq7695n00000gn/T/ipykernel_13994/3927743529.py:19: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  ].sum()["count"]
/var/folders/6v/w9nn6c_n4qdbrjwfnq7695n00000gn/T/ipykernel_13994/3927743529.py:25: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  ].sum()["count"]

nan

In [5]:
from protest_impact.data.news.sources.mediacloud import get_profile

get_profile()

{'active': 1,
 'api_key': 'a412837f2a6ae4f8c6d56e31292d67a4f16848e6a95e1501d5578d4f4d60065e',
 'auth_roles': ['tm-readonly'],
 'auth_users_id': 19952,
 'created_date': '2023-02-21T13:38:31+00:00',
 'email': 'ripraprup@web.de',
 'full_name': 'David Pomerenke',
 'has_consented': 1,
 'limits': {'max_topic_stories': 100000,
  'weekly': {'requested_items': {'limit': 100000, 'used': 5},
   'requests': {'limit': 10000, 'used': 5}}},
 'notes': 'In my master thesis in Artificial Intelligence at Maastricht University I want to investigate the causal impact of protest movements on public discourse.'}